<?php

namespace App;

class AddAcfField
{
    public function __construct()
    {
        add_action('acf/include_fields', [$this, 'add_acf_custom_landing_pages_field']);
    }

    public function add_acf_custom_landing_pages_field()
    {
	    if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		    return;
	    }

	    acf_add_local_field_group( array(
		    'key' => 'group_651af82634aa4',
		    'title' => 'Airmenzies Custom Landing Pages',
		    'fields' => array(
			    array(
				    'key' => 'field_651af826129f2',
				    'label' => 'Header',
				    'name' => '',
				    'aria-label' => '',
				    'type' => 'tab',
				    'instructions' => '',
				    'required' => 0,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'placement' => 'left',
				    'endpoint' => 0,
			    ),
			    array(
				    'key' => 'field_653fc294874ec',
				    'label' => 'AMI Logo',
				    'name' => 'ami_logo',
				    'aria-label' => '',
				    'type' => 'image',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'return_format' => 'url',
				    'library' => 'all',
				    'min_width' => '',
				    'min_height' => '',
				    'min_size' => '',
				    'max_width' => '',
				    'max_height' => '',
				    'max_size' => '',
				    'mime_types' => '',
				    'preview_size' => 'medium',
			    ),
			    array(
				    'key' => 'field_651af965af500',
				    'label' => 'Main heading',
				    'name' => 'header_main_heading',
				    'aria-label' => '',
				    'type' => 'text',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'default_value' => '',
				    'maxlength' => '',
				    'placeholder' => '',
				    'prepend' => '',
				    'append' => '',
			    ),
			    array(
				    'key' => 'field_651af9abaf501',
				    'label' => 'Content heading',
				    'name' => 'header_content_heading',
				    'aria-label' => '',
				    'type' => 'text',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'default_value' => '',
				    'maxlength' => '',
				    'placeholder' => '',
				    'prepend' => '',
				    'append' => '',
			    ),
			    array(
				    'key' => 'field_651afbb1b46e2',
				    'label' => 'Content text',
				    'name' => 'header_content_text',
				    'aria-label' => '',
				    'type' => 'text',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'default_value' => '',
				    'maxlength' => '',
				    'placeholder' => '',
				    'prepend' => '',
				    'append' => '',
			    ),
			    array(
				    'key' => 'field_651afa4faf502',
				    'label' => 'Button',
				    'name' => 'header_cta_button',
				    'aria-label' => '',
				    'type' => 'link',
				    'instructions' => '',
				    'required' => 0,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'return_format' => 'array',
			    ),
			    array(
				    'key' => 'field_6551192215bc9',
				    'label' => 'Popup',
				    'name' => 'header_popup',
				    'aria-label' => '',
				    'type' => 'post_object',
				    'instructions' => '',
				    'required' => 0,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'post_type' => array(
					    0 => 'popup',
				    ),
				    'post_status' => '',
				    'taxonomy' => '',
				    'return_format' => 'id',
				    'multiple' => 0,
				    'allow_null' => 1,
				    'bidirectional' => 0,
				    'ui' => 1,
				    'bidirectional_target' => array(
				    ),
			    ),
			    array(
				    'key' => 'field_651afa73af503',
				    'label' => 'Image',
				    'name' => 'header_image',
				    'aria-label' => '',
				    'type' => 'image',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'return_format' => 'url',
				    'library' => 'all',
				    'min_width' => '',
				    'min_height' => '',
				    'min_size' => '',
				    'max_width' => '',
				    'max_height' => '',
				    'max_size' => '',
				    'mime_types' => '',
				    'preview_size' => 'medium',
			    ),
			    array(
				    'key' => 'field_651b35f139df9',
				    'label' => 'Cards',
				    'name' => '',
				    'aria-label' => '',
				    'type' => 'tab',
				    'instructions' => '',
				    'required' => 0,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'placement' => 'left',
				    'endpoint' => 0,
			    ),
			    array(
				    'key' => 'field_651b361e39dfa',
				    'label' => 'Heading',
				    'name' => 'cards_heading',
				    'aria-label' => '',
				    'type' => 'text',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'default_value' => '',
				    'maxlength' => '',
				    'placeholder' => '',
				    'prepend' => '',
				    'append' => '',
			    ),
			    array(
				    'key' => 'field_655115a7f5c93',
				    'label' => 'Cards',
				    'name' => 'cards',
				    'aria-label' => '',
				    'type' => 'repeater',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'layout' => 'row',
				    'pagination' => 0,
				    'min' => 0,
				    'max' => 0,
				    'collapsed' => '',
				    'button_label' => 'Add Row',
				    'rows_per_page' => 20,
				    'sub_fields' => array(
					    array(
						    'key' => 'field_6551161cf5c94',
						    'label' => 'Heading',
						    'name' => 'heading',
						    'aria-label' => '',
						    'type' => 'text',
						    'instructions' => '',
						    'required' => 1,
						    'conditional_logic' => 0,
						    'wrapper' => array(
							    'width' => '',
							    'class' => '',
							    'id' => '',
						    ),
						    'default_value' => '',
						    'maxlength' => '',
						    'placeholder' => '',
						    'prepend' => '',
						    'append' => '',
						    'parent_repeater' => 'field_655115a7f5c93',
					    ),
					    array(
						    'key' => 'field_6551162bf5c95',
						    'label' => 'Text',
						    'name' => 'text',
						    'aria-label' => '',
						    'type' => 'wysiwyg',
						    'instructions' => '',
						    'required' => 1,
						    'conditional_logic' => 0,
						    'wrapper' => array(
							    'width' => '',
							    'class' => '',
							    'id' => '',
						    ),
						    'default_value' => '',
						    'tabs' => 'visual',
						    'toolbar' => 'basic',
						    'media_upload' => 0,
						    'delay' => 0,
						    'parent_repeater' => 'field_655115a7f5c93',
					    ),
					    array(
						    'key' => 'field_6551163df5c96',
						    'label' => 'Button',
						    'name' => 'button',
						    'aria-label' => '',
						    'type' => 'link',
						    'instructions' => '',
						    'required' => 0,
						    'conditional_logic' => 0,
						    'wrapper' => array(
							    'width' => '',
							    'class' => '',
							    'id' => '',
						    ),
						    'return_format' => 'array',
						    'parent_repeater' => 'field_655115a7f5c93',
					    ),
					    array(
						    'key' => 'field_65511657f5c97',
						    'label' => 'Icon',
						    'name' => 'icon',
						    'aria-label' => '',
						    'type' => 'image',
						    'instructions' => '',
						    'required' => 1,
						    'conditional_logic' => 0,
						    'wrapper' => array(
							    'width' => '',
							    'class' => '',
							    'id' => '',
						    ),
						    'return_format' => 'url',
						    'library' => 'all',
						    'min_width' => '',
						    'min_height' => '',
						    'min_size' => '',
						    'max_width' => '',
						    'max_height' => '',
						    'max_size' => '',
						    'mime_types' => '',
						    'preview_size' => 'medium',
						    'parent_repeater' => 'field_655115a7f5c93',
					    ),
				    ),
			    ),
			    array(
				    'key' => 'field_651bebfa02c5e',
				    'label' => 'Card end',
				    'name' => '',
				    'aria-label' => '',
				    'type' => 'accordion',
				    'instructions' => '',
				    'required' => 0,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'open' => 0,
				    'multi_expand' => 0,
				    'endpoint' => 1,
			    ),
			    array(
				    'key' => 'field_651be64fd6177',
				    'label' => 'Video',
				    'name' => '',
				    'aria-label' => '',
				    'type' => 'tab',
				    'instructions' => '',
				    'required' => 0,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'placement' => 'left',
				    'endpoint' => 0,
			    ),
			    array(
				    'key' => 'field_651be65ed6178',
				    'label' => 'Heading',
				    'name' => 'video_heading',
				    'aria-label' => '',
				    'type' => 'text',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'default_value' => '',
				    'maxlength' => '',
				    'placeholder' => '',
				    'prepend' => '',
				    'append' => '',
			    ),
			    array(
				    'key' => 'field_651be66fd6179',
				    'label' => 'Video',
				    'name' => 'video_video',
				    'aria-label' => '',
				    'type' => 'oembed',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'width' => '',
				    'height' => '',
			    ),
			    array(
				    'key' => 'field_651bf5949f54f',
				    'label' => 'Testimonials',
				    'name' => '',
				    'aria-label' => '',
				    'type' => 'tab',
				    'instructions' => '',
				    'required' => 0,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'placement' => 'left',
				    'endpoint' => 0,
			    ),
			    array(
				    'key' => 'field_65511e4b09762',
				    'label' => 'Enable Testimonials',
				    'name' => 'enable_testimonials',
				    'aria-label' => '',
				    'type' => 'true_false',
				    'instructions' => '',
				    'required' => 0,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'message' => '',
				    'default_value' => 0,
				    'ui_on_text' => '',
				    'ui_off_text' => '',
				    'ui' => 1,
			    ),
			    array(
				    'key' => 'field_651bf5a09f550',
				    'label' => 'Heading',
				    'name' => 'testimonials_heading',
				    'aria-label' => '',
				    'type' => 'text',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => array(
					    array(
						    array(
							    'field' => 'field_65511e4b09762',
							    'operator' => '==',
							    'value' => '1',
						    ),
					    ),
				    ),
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'default_value' => '',
				    'maxlength' => '',
				    'placeholder' => '',
				    'prepend' => '',
				    'append' => '',
			    ),
			    array(
				    'key' => 'field_65511bf4f8cc9',
				    'label' => 'Testimonials',
				    'name' => 'testimonials',
				    'aria-label' => '',
				    'type' => 'repeater',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => array(
					    array(
						    array(
							    'field' => 'field_65511e4b09762',
							    'operator' => '==',
							    'value' => '1',
						    ),
					    ),
				    ),
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'layout' => 'row',
				    'pagination' => 0,
				    'min' => 4,
				    'max' => 0,
				    'collapsed' => '',
				    'button_label' => 'Add Row',
				    'rows_per_page' => 20,
				    'sub_fields' => array(
					    array(
						    'key' => 'field_65511c09f8cca',
						    'label' => 'Name',
						    'name' => 'name',
						    'aria-label' => '',
						    'type' => 'text',
						    'instructions' => '',
						    'required' => 1,
						    'conditional_logic' => 0,
						    'wrapper' => array(
							    'width' => '',
							    'class' => '',
							    'id' => '',
						    ),
						    'default_value' => '',
						    'maxlength' => '',
						    'placeholder' => '',
						    'prepend' => '',
						    'append' => '',
						    'parent_repeater' => 'field_65511bf4f8cc9',
					    ),
					    array(
						    'key' => 'field_65511c13f8ccb',
						    'label' => 'Company',
						    'name' => 'company',
						    'aria-label' => '',
						    'type' => 'text',
						    'instructions' => '',
						    'required' => 1,
						    'conditional_logic' => 0,
						    'wrapper' => array(
							    'width' => '',
							    'class' => '',
							    'id' => '',
						    ),
						    'default_value' => '',
						    'maxlength' => '',
						    'placeholder' => '',
						    'prepend' => '',
						    'append' => '',
						    'parent_repeater' => 'field_65511bf4f8cc9',
					    ),
					    array(
						    'key' => 'field_65511c1af8ccc',
						    'label' => 'Quote',
						    'name' => 'quote',
						    'aria-label' => '',
						    'type' => 'text',
						    'instructions' => '',
						    'required' => 1,
						    'conditional_logic' => 0,
						    'wrapper' => array(
							    'width' => '',
							    'class' => '',
							    'id' => '',
						    ),
						    'default_value' => '',
						    'maxlength' => '',
						    'placeholder' => '',
						    'prepend' => '',
						    'append' => '',
						    'parent_repeater' => 'field_65511bf4f8cc9',
					    ),
				    ),
			    ),
			    array(
				    'key' => 'field_6527d55484f8e',
				    'label' => 'Testimonials end',
				    'name' => '',
				    'aria-label' => '',
				    'type' => 'accordion',
				    'instructions' => '',
				    'required' => 0,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'open' => 0,
				    'multi_expand' => 0,
				    'endpoint' => 1,
			    ),
			    array(
				    'key' => 'field_651bfa0fcb3a6',
				    'label' => 'Booking',
				    'name' => '',
				    'aria-label' => '',
				    'type' => 'tab',
				    'instructions' => '',
				    'required' => 0,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'placement' => 'left',
				    'endpoint' => 0,
			    ),
			    array(
				    'key' => 'field_651bfa1be9ed6',
				    'label' => 'Heading',
				    'name' => 'booking_heading',
				    'aria-label' => '',
				    'type' => 'text',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'default_value' => '',
				    'maxlength' => '',
				    'placeholder' => '',
				    'prepend' => '',
				    'append' => '',
			    ),
			    array(
				    'key' => 'field_651bfb8432f6b',
				    'label' => 'Callback',
				    'name' => '',
				    'aria-label' => '',
				    'type' => 'accordion',
				    'instructions' => '',
				    'required' => 0,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'open' => 0,
				    'multi_expand' => 0,
				    'endpoint' => 0,
			    ),
			    array(
				    'key' => 'field_651bfb9e32f6d',
				    'label' => 'Heading',
				    'name' => 'booking_callback_heading',
				    'aria-label' => '',
				    'type' => 'text',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'default_value' => '',
				    'maxlength' => '',
				    'placeholder' => '',
				    'prepend' => '',
				    'append' => '',
			    ),
			    array(
				    'key' => 'field_651bfbaf32f6e',
				    'label' => 'Icon',
				    'name' => 'booking_callback_icon',
				    'aria-label' => '',
				    'type' => 'image',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'return_format' => 'url',
				    'library' => 'all',
				    'min_width' => '',
				    'min_height' => '',
				    'min_size' => '',
				    'max_width' => '',
				    'max_height' => '',
				    'max_size' => '',
				    'mime_types' => '',
				    'preview_size' => 'medium',
			    ),
			    array(
				    'key' => 'field_651bfbc032f6f',
				    'label' => 'Text',
				    'name' => 'booking_callback_text',
				    'aria-label' => '',
				    'type' => 'text',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'default_value' => '',
				    'maxlength' => '',
				    'placeholder' => '',
				    'prepend' => '',
				    'append' => '',
			    ),
			    array(
				    'key' => 'field_651bfbca32f70',
				    'label' => 'Button',
				    'name' => 'booking_callback_button',
				    'aria-label' => '',
				    'type' => 'text',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'default_value' => '',
				    'maxlength' => '',
				    'placeholder' => '',
				    'prepend' => '',
				    'append' => '',
			    ),
			    array(
				    'key' => 'field_651c112df159a',
				    'label' => 'Popup',
				    'name' => 'booking_callback_popup',
				    'aria-label' => '',
				    'type' => 'post_object',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'post_type' => array(
					    0 => 'popup',
				    ),
				    'post_status' => '',
				    'taxonomy' => '',
				    'return_format' => 'id',
				    'multiple' => 0,
				    'allow_null' => 0,
				    'bidirectional' => 0,
				    'ui' => 1,
				    'bidirectional_target' => array(
				    ),
			    ),
			    array(
				    'key' => 'field_651bfbecf1ba5',
				    'label' => 'Discussion',
				    'name' => '',
				    'aria-label' => '',
				    'type' => 'accordion',
				    'instructions' => '',
				    'required' => 0,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'open' => 0,
				    'multi_expand' => 0,
				    'endpoint' => 0,
			    ),
			    array(
				    'key' => 'field_651bfc37f1baa',
				    'label' => 'Heading',
				    'name' => 'booking_discussion_heading',
				    'aria-label' => '',
				    'type' => 'text',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'default_value' => '',
				    'maxlength' => '',
				    'placeholder' => '',
				    'prepend' => '',
				    'append' => '',
			    ),
			    array(
				    'key' => 'field_651bfc36f1ba9',
				    'label' => 'Icon',
				    'name' => 'booking_discussion_icon',
				    'aria-label' => '',
				    'type' => 'image',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'return_format' => 'url',
				    'library' => 'all',
				    'min_width' => '',
				    'min_height' => '',
				    'min_size' => '',
				    'max_width' => '',
				    'max_height' => '',
				    'max_size' => '',
				    'mime_types' => '',
				    'preview_size' => 'medium',
			    ),
			    array(
				    'key' => 'field_651bfc7ef1bab',
				    'label' => 'Text',
				    'name' => 'booking_discussion_text',
				    'aria-label' => '',
				    'type' => 'text',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'default_value' => '',
				    'maxlength' => '',
				    'placeholder' => '',
				    'prepend' => '',
				    'append' => '',
			    ),
			    array(
				    'key' => 'field_651bfc34f1ba7',
				    'label' => 'Button',
				    'name' => 'booking_discussion_button',
				    'aria-label' => '',
				    'type' => 'text',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'default_value' => '',
				    'maxlength' => '',
				    'placeholder' => '',
				    'prepend' => '',
				    'append' => '',
			    ),
			    array(
				    'key' => 'field_651c1114f1599',
				    'label' => 'Popup',
				    'name' => 'booking_discussion_popup',
				    'aria-label' => '',
				    'type' => 'post_object',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'post_type' => array(
					    0 => 'popup',
				    ),
				    'post_status' => '',
				    'taxonomy' => '',
				    'return_format' => 'id',
				    'multiple' => 0,
				    'allow_null' => 0,
				    'bidirectional' => 0,
				    'ui' => 1,
				    'bidirectional_target' => array(
				    ),
			    ),
			    array(
				    'key' => 'field_651bfc20f1ba6',
				    'label' => 'Booking end',
				    'name' => '',
				    'aria-label' => '',
				    'type' => 'accordion',
				    'instructions' => '',
				    'required' => 0,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'open' => 0,
				    'multi_expand' => 0,
				    'endpoint' => 1,
			    ),
			    array(
				    'key' => 'field_65547c8bfd3ec',
				    'label' => 'Footer',
				    'name' => '',
				    'aria-label' => '',
				    'type' => 'tab',
				    'instructions' => '',
				    'required' => 0,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'placement' => 'top',
				    'endpoint' => 0,
			    ),
			    array(
				    'key' => 'field_65547c99fd3ee',
				    'label' => 'Main Text',
				    'name' => 'footer_main_text',
				    'aria-label' => '',
				    'type' => 'textarea',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'default_value' => '',
				    'maxlength' => '',
				    'rows' => '',
				    'placeholder' => '',
				    'new_lines' => 'br',
			    ),
			    array(
				    'key' => 'field_65547cc5fd3ef',
				    'label' => 'Privacy Policy Link',
				    'name' => 'footer_privacy_policy_link',
				    'aria-label' => '',
				    'type' => 'url',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'default_value' => '',
				    'placeholder' => '',
			    ),
			    array(
				    'key' => 'field_65547cdcfd3f0',
				    'label' => 'FAQ Link',
				    'name' => 'footer_faq_link',
				    'aria-label' => '',
				    'type' => 'url',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'default_value' => '',
				    'placeholder' => '',
			    ),
			    array(
				    'key' => 'field_65547cf8fd3f1',
				    'label' => 'Contact Link',
				    'name' => 'footer_contact_link',
				    'aria-label' => '',
				    'type' => 'url',
				    'instructions' => '',
				    'required' => 1,
				    'conditional_logic' => 0,
				    'wrapper' => array(
					    'width' => '',
					    'class' => '',
					    'id' => '',
				    ),
				    'default_value' => '',
				    'placeholder' => '',
			    ),
		    ),
		    'location' => array(
			    array(
				    array(
					    'param' => 'page_template',
					    'operator' => '==',
					    'value' => 'templates/callback-discussion.php',
				    ),
			    ),
		    ),
		    'menu_order' => 0,
		    'position' => 'acf_after_title',
		    'style' => 'default',
		    'label_placement' => 'top',
		    'instruction_placement' => 'label',
		    'hide_on_screen' => array(
			    0 => 'the_content',
			    1 => 'discussion',
			    2 => 'comments',
		    ),
		    'active' => true,
		    'description' => '',
		    'show_in_rest' => 0,
	    ) );
    }
}
